language: ruby
rvm:
  - 1.9.2
  - 1.9.3
# uncomment this line if your project needs to run something other than `rake`:
script: 
  - bundle exec rspec spec
  - bundle exec rspec spec/requests -t type:request
env: RAILS_ENV=test
before_script: 
  - psql -c 'create database codechallenge_test;' -U postgres
  - bundle exec rake db:migrate db:test:prepare